# Generated by Django 3.1.1 on 2020-10-14 23:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_notification_readynotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='last_checked',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
