# Generated by Django 3.1.1 on 2020-10-14 23:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_notification_last_checked'),
    ]

    operations = [
        migrations.AddField(
            model_name='readynotification',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
