# Generated by Django 3.1.1 on 2020-10-17 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_track'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='state',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
