# Generated by Django 3.1.1 on 2020-10-20 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_auto_20201020_0400'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trackstock',
            old_name='days',
            new_name='weeks',
        ),
    ]
