# Generated by Django 3.1.1 on 2020-10-20 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_auto_20201021_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackstock',
            name='creation_time',
            field=models.DateField(),
        ),
    ]
