# Generated by Django 3.1.1 on 2020-11-08 08:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0019_auto_20201108_1015'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockOperationHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_number', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('stock_buy_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('stock_price', models.FloatField(null=True)),
                ('stock_operation', models.BooleanField(default=False)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.stock')),
            ],
        ),
        migrations.CreateModel(
            name='UserStockHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_operation_history', models.ManyToManyField(to='myapp.StockOperationHistory')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
