# Generated by Django 3.1.3 on 2020-11-24 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_cryptocurrency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='change_percent',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
